apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-gossip-ring
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gossip-ring
      port: {{ include "mimir.memberlistBindPort" . }}
      appProtocol: tcp
      protocol: TCP
      targetPort: {{ include "mimir.memberlistBindPort" . }}
  publishNotReadyAddresses: true
  selector:
    {{- include "mimir.selectorLabels" . | nindent 4 }}
