{{- if not .Values.useExternalConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
{{- if eq .Values.configStorageType "Secret" }}
data:
  mimir.yaml: {{ include "mimir.calculatedConfig" . | b64enc }}
{{- else }}
data:
  mimir.yaml: |
    {{ include "mimir.calculatedConfig" . | nindent 4 }}
{{- end -}}
{{- end }}
