apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}-runtime
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  runtime.yaml: |
    {{ tpl (toYaml .Values.runtimeConfig) . | nindent 4 }}
